server:
  port: 2778

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pavsod_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lqj18340237677
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭自动驼峰转换
