app:
  name: "PAV-SOD全景级音视频显著性检测系统"
  version: "1.0.0"
  #阿里云存储配置
  oss:
    endpoint: "https://oss-cn-beijing.aliyuncs.com"
    bucketName: "pavsod-oss"
    region: "cn-beijing"
  default:
    photo_url: "https://pavsod-oss.oss-cn-beijing.aliyuncs.com/2042664572095430658.png"
    jwt_secret: "liqingjiang"
  flask:
    host: localhost
    port: 5000

server:
  port: 2778

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pavsod_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lqj18340237677
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  # 关闭自动驼峰转换
